version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pipenv install
            pip install flask
            pip install --upgrade setuptools
            pip install markupsafe==1.1.1
      - run:
          name: package application
          command: |
            # . venv/bin/activate
            zip code.zip api/api_generator.py
            pwd
            ls
      - persist_to_workspace:
          root: .
          paths:
            - code.zip      
      - run:
          name: Install AWS CLI
          command: pip install awscli
      - run:
          name: configure AWS credentials
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION
      - run:
          name: upload to s3
          command: |
            pwd
            ls
            aws s3 cp code.zip s3://lambdafunctionpackagedfile/code.zip      
  deploy:
    docker:
      - image: circleci/python:3.6
    # parameters:
    #   s3-bucket-name:
    #     type: string
    #     default: test-api-circleci
    #   stack-name:
    #     type: string
    #     default: testapistack
      
    steps:
      # - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Install AWS CLI
          command: pip install awscli
      - run:
          name: Install AWS SAM CLI
          command: |
            pip install aws-sam-cli
      - run:
          name: configure AWS credentials
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION
      - run:
          name: verifying working directory
          command: |
            pwd
            ls -la
      - run:
          name: Run api_generator.py
          command: |
            python -m venv venv
            pwd
            ls
            . venv/bin/activate
            pwd
            ls
            pip install --upgrade pip
            pipenv install
            pip install flask
            pip install --upgrade setuptools
            pip install markupsafe==1.1.1
            # python api_generator.py
            python code.zip
workflows:
  version: 2
  testdeploy:
    jobs:
      - build:
          name: package api
          context: aws-credential-dev
      - deploy:
          name: deploy-api
          requires:
            - package api
          context: aws-credential-dev
          filters:
            branches:
              only: main
                                
              
